#### splitting the data normally and then using k folds 

#### comparing the accuracies of three different models
###### 1. Logistic regression\
###### 2. random forest 
###### 3. svm 

#### then using cross_val_score function to do the same


In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt


from sklearn.datasets import load_digits
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target ,test_size=0.3)

In [16]:
y_train

array([7, 1, 0, ..., 1, 8, 6])

In [5]:
#logistic regression

lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9592592592592593

In [7]:
#SVM

svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.4703703703703704

In [9]:
#Random Forest

rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)


0.9574074074074074

##### these techniques of splitting the dataset provide varying accuracies because of the change in the samples

#### using k fold cross validation to split the dataset and train the model

## K Folds Cross Validation

In [39]:
from sklearn.model_selection import KFold
kf= KFold(n_splits = 3) #n_splits = number of folds

In [40]:
#creating a finction to predict and calculate the score of different models

def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [41]:
get_score(SVC(),x_train, x_test, y_train, y_test)

0.9649415692821369

In [42]:
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits=3)

In [43]:
scores_logistic = []
scores_svm = []
scores_rf = []

In [44]:
for train_index, test_index in folds.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [45]:
scores_logistic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [46]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [47]:
scores_rf

[0.9398998330550918, 0.9465776293823038, 0.9248747913188647]

#### doing the same thing with cross_val_score function

In [48]:
from sklearn.model_selection import cross_val_score


In [49]:
cross_val_score(RandomForestClassifier(),digits.data, digits.target)

array([0.93611111, 0.91666667, 0.94986072, 0.95821727, 0.92200557])

In [50]:
cross_val_score(SVC(),digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [51]:
cross_val_score(LogisticRegression(),digits.data, digits.target)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])